"""Record the installed transitive closure without upgrading any dependency.

Run in the reviewed Python 3.12 development environment, then validate on both
target platforms. Only requirements*.in are direct inputs; lock files are output.
"""

import argparse
import importlib.metadata as metadata

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

from scripts.common import ROOT, require_python312


def closure(inputs):
    pending = [Requirement(line) for line in inputs if line and not line.startswith("#")]
    seen, result = set(), {}
    while pending:
        req = pending.pop()
        name = canonicalize_name(req.name)
        key = (name, tuple(sorted(req.extras)))
        if key in seen:
            continue
        seen.add(key)
        version = metadata.version(name)
        if version not in req.specifier:
            raise ValueError(f"Kurulu {name} sürümü doğrudan/dolaylı kısıtı sağlamıyor.")
        result[name] = version
        for line in metadata.requires(name) or []:
            dep = Requirement(line)
            for platform, system in (("win32", "Windows"), ("linux", "Linux")):
                env = {
                    **default_environment(),
                    "sys_platform": platform,
                    "platform_system": system,
                    "platform_machine": "AMD64" if platform == "win32" else "x86_64",
                }
                if dep.marker is None or any(
                    dep.marker.evaluate({**env, "extra": extra}) for extra in ("", *req.extras)
                ):
                    pending.append(dep)
                    break
    return result


def lock_text(packages):
    return (
        "# Generated by python -m scripts.lock_dependencies; CPython 3.12, Windows/Linux x64.\n"
        "# Exact direct and transitive versions; see docs/dependencies.md.\n"
        + "".join(f"{name}=={version}\n" for name, version in sorted(packages.items()))
    )


def main():
    require_python312()
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    runtime = (ROOT / "requirements.in").read_text().splitlines()
    dev = (ROOT / "requirements-dev.in").read_text().splitlines()
    for filename, content in (
        ("requirements.txt", lock_text(closure(runtime))),
        ("requirements-dev.txt", lock_text(closure(runtime + dev))),
    ):
        path = ROOT / filename
        if args.check:
            if path.read_text() != content:
                raise RuntimeError(f"{filename}: kurulu ortam ve lock uyuşmuyor.")
        else:
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
